# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Forward minio port
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "..", "/home/vagrant/gopath/src/github.com/minio/minio"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

  config.ssh.username = "vagrant"
  config.vm.provision "shell", path: "minio-test-provision.sh"
end
